### ISSUE TITLE
Achievement stat not work 

### ISSUE THREAD

**Issue by xteriumboy** [joancefet/Beta7#11]
Achievement stat not work 

Photo :
http://prnt.sc/b8ckw2

**Comment by xteriumboy** [comment]
fixed

**Comment by joancefet** [comment]
how?

**Comment by xteriumboy** [comment]
class.AbstractPage.php

`//ACHIEVEMENT TECH HACKER
        $hacker_reward_am = 20;
        $hacker_reward_points = 11;
        $hacker_reward_points = $hacker_reward_points + ($USER['achievements_tech_hacker'] * $hacker_reward_points);
        $hacker_reward_am = $hacker_reward_am + ($USER['achievements_tech_hacker'] * $hacker_reward_am);
        $next_level = $USER['achievements_tech_hacker'] + 1;
        if ($USER['computer_tech'] >= (3 * $USER['achievements_tech_hacker']) + 3){
        $GLOBALS['DATABASE']->query("UPDATE ".USERS." set`achievements_tech_hacker`=`achievements_tech_hacker`+ '1', antimatter = antimatter + ".$hacker_reward_am." where`id`= '".$USER['id']."';");
        $msg = '<img alt="" style="float:left; width:60px; margin-right:6px;" src="styles/images/achiev/ach_computer_tech.png">'.$LNG['ach_reached'].': <span class="achiev_mes_head">hacker lvl. '.$next_level.'</span><br> '.$LNG['ach_receive'].':<br> '.$hacker_reward_am.' '.$LNG['tech'][922].' <br> '.$hacker_reward_points.' '.$LNG['ach_points'].'';
        SendSimpleMessage($USER['id'], '', TIMESTAMP, 4, 'System', 'Achievements', $msg);
        }`

see

`$GLOBALS['DATABASE']->query("UPDATE ".USERS." set`achievements_tech_hacker`=`achievements_tech_hacker`+ '1', antimatter = antimatter + ".$hacker_reward_am." where`id`= '".$USER['id']."';");`

no $hacker_reward_points = 11; 

need to add 

Achi_pts = Achi_pts + ".$hacker_reward_points."

**Comment by xteriumboy** [comment]
class.ShowAchievementsPage.php

you have 

387line `'ach_points_total'` => $AchPoints,`

my code is  `'Achi_Pts' => $USER['Achi_pts'],`

**Comment by xteriumboy** [comment]
you need to change the  class.statbuilder.php

`$Return['Users']   = $GLOBALS['DATABASE']->query('SELECT SQL_BIG_RESULT DISTINCT '.$selected_tech.$select_fleets.$select_defenses.' u.id, u.Achi_pts, u.ally_id, u.authlevel, u.bana, u.universe, u.username, s.tech_rank AS old_tech_rank, s.build_rank AS old_build_rank, s.defs_rank AS old_defs_rank, s.fleet_rank AS old_fleet_rank, s.total_rank AS old_total_rank, s.ach_rank AS ach_old_rank FROM '.USERS.' as u LEFT JOIN '.STATPOINTS.' as s ON s.stat_type = 1 AND s.id_owner = u.id LEFT JOIN '.PLANETS.' as p ON u.id = p.id_owner GROUP BY s.id_owner, u.id, u.authlevel;');
        $Return['Alliance'] = $GLOBALS['DATABASE']->query('SELECT SQL_BIG_RESULT DISTINCT a.id, a.ally_universe, s.tech_rank AS old_tech_rank, s.build_rank AS old_build_rank, s.defs_rank AS old_defs_rank, s.fleet_rank AS old_fleet_rank, s.total_rank AS old_total_rank, s.ach_rank AS ach_old_rank FROM '.ALLIANCE.' as a LEFT JOIN '.STATPOINTS.' as s ON s.stat_type = 2 AND s.id_owner = a.id;');
`

`$AchPoints = $USER['Achi_pts'];`

`while($CurUser = $GLOBALS['DATABASE']->fetch_array($RankQry))
            {
                $QryUpdateStats .= "UPDATE ".STATPOINTS." SET ach_rank = '". $Ach[$CurUser['id_owner']] ."', tech_rank = '". $tech[$CurUser['id_owner']] ."', build_rank = '". $build[$CurUser['id_owner']] ."', defs_rank = '". $defs[$CurUser['id_owner']] ."', fleet_rank = '". $fleet[$CurUser['id_owner']] ."', total_rank = '". $Rank ."' WHERE stat_type = '1' AND id_owner = '". $CurUser['id_owner'] ."';";
                $Rank++;
            }`

`$Rank           = 1;
            $RankQry        = $GLOBALS['DATABASE']->query("SELECT s.id_owner FROM ".STATPOINTS." as s WHERE s.universe = '".$Uni."' AND s.stat_type = '2' ORDER BY total_points DESC;");

```
        while($CurUser = $GLOBALS['DATABASE']->fetch_array($RankQry))
        {
            $QryUpdateStats .= "UPDATE ".STATPOINTS." SET ach_rank = '". $Ach[$CurUser['id_owner']] ."', tech_rank = '". $tech[$CurUser['id_owner']] ."', build_rank = '". $build[$CurUser['id_owner']] ."', defs_rank = '". $defs[$CurUser['id_owner']] ."', fleet_rank = '". $fleet[$CurUser['id_owner']] ."', total_rank = '". $Rank ."' WHERE stat_type = '2' AND id_owner = '". $CurUser['id_owner'] ."';";
            $Rank++;
        }`
```

`(isset($UserData['ach_old_rank']) ? $UserData['ach_old_rank'] : 0).", ".`

`(isset($AllyPoints['ach_old_rank']) ? $AllyPoints['ach_old_rank'] : 0).", ".`

**Comment by joancefet** [comment]
I think it does not work properly.

**Comment by xteriumboy** [comment]
this is my fixed Achievements version!

**Comment by xteriumboy** [comment]
http://prnt.sc/b8f524

**Comment by joancefet** [comment]
Have you checked manually?

112.800????? This is too much.

**Comment by xteriumboy** [comment]
hacker_reward_am = 20; $hacker_reward_points = 11;

$hacker_reward_points = 11;  changed all reward
