### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by xteriumboy** [joancefet/Beta7#2]
Fatal error: Uncaught exception 'ErrorException' with message 'Undefined offset: 8192' in C:\xampp\htdocs\beta7\includes\GeneralFunctions.php:766 Stack trace: #0 C:\xampp\htdocs\beta7\includes\GeneralFunctions.php(766): errorHandler(8, 'Undefined offse...', 'C:\xampp\htdocs...', 766, Array) #1 [internal function]: exceptionHandler(Object(ErrorException)) #2 {main} thrown in C:\xampp\htdocs\beta7\includes\GeneralFunctions.php on line 766

**Comment by joancefet** [comment]
This issue happened again?

**Comment by joancefet** [comment]
Closed for inactivity.
