### ISSUE TITLE
Training not work 

### ISSUE THREAD

**Issue by xteriumboy** [joancefet/Beta7#3]
Training not work ,some Training step 

Issue: Missing argument 20 for FleetFunctions::sendFleet(), called in /includes/pages/game/class.ShowShipyardPage.php on line 571 and defined
File: /includes/classes/class.FleetFunctions.php (Line 416)
URL: http://localhost/beta7/game.php?page=shipyard&mode=defense
PHP: Version 5.6.15 [ apache2handler ]
MySQL: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $

Debug Track:
#0 /includes/classes/class.FleetFunctions.php(416): errorHandler(2, 'Missing argumen...', 'C://xampp//htdocs...', 416, Array)
#1 /includes/pages/game/class.ShowShipyardPage.php(571): FleetFunctions::sendFleet(Array, '1', 1, 1, 1, 1, 1, 1, '1', '1', '1', '1', '1', '1', Array, 1463346717, 1463346717, 1463346775, 0)
#2 /game.php(40): ShowShipyardPage->show()
#3 {main}

**Comment by joancefet** [comment]
Fixed.

**Comment by xteriumboy** [comment]
Get this again !!!

Issue: Missing argument 20 for FleetFunctions::sendFleet(), called in /includes/pages/game/class.ShowBuildingsPage.php on line 485 and defined
File: /includes/classes/class.FleetFunctions.php (Line 416)
URL: http://localhost/beta7/game.php?page=buildings
PHP: Version 5.6.15 [ apache2handler ]
MySQL: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $

Debug Track:
#0 /includes/classes/class.FleetFunctions.php(416): errorHandler(2, 'Missing argumen...', 'C://xampp//htdocs...', 416, Array)
#1 /includes/pages/game/class.ShowBuildingsPage.php(485): FleetFunctions::sendFleet(Array, '6', 1, 1, 1, 1, 1, 1, '4', '5', '1', '1', '6', '1', Array, 1463355210, 1463355210, 1463355250, 0)
#2 /game.php(40): ShowBuildingsPage->show()
#3 {main}

**Comment by xteriumboy** [comment]
Issue: SQL Error: Out of range value for column 'light_hunter' at row 1

Query Code: LOCK TABLE uni1_fleets_alarm WRITE, uni1_log_fleets WRITE, uni1_fleet_event WRITE, uni1_fleets WRITE, uni1_planets WRITE; UPDATE uni1_planets SET light_hunter = light_hunter - 8, heavy_hunter = heavy_hunter - 5, crusher = crusher - 3 WHERE id = 1; INSERT INTO uni1_fleets SET fleet_owner = 1, fleet_target_owner = 4, fleet_mission = 1, fleet_amount = 16, fleet_array = '204,8;205,5;206,3', fleet_universe = 1, fleet_start_time = 1463355520, fleet_end_stay = 1463355520, fleet_end_time = 1463355578, fleet_start_id = 1, fleet_start_galaxy = 1, fleet_start_system = 1, fleet_start_planet = 1, fleet_start_type = 1, fleet_end_id = 5, fleet_end_galaxy = 1, fleet_end_system = 1, fleet_end_planet = 6, fleet_end_type = 1, fleet_resource_metal = 0, fleet_resource_crystal = 0, fleet_resource_deuterium = 0, fleet_group = 0, fleet_target_obj = 0, tickinicial = 0, tickfinal = 9, tickretorno = 18, start_time = 1463355462; SET @fleetID = LAST_INSERT_ID(); INSERT INTO uni1_fleets_alarm SET fleet_owner = 1, fleet_target_owner = 4, fleet_mission = 1, fleet_amount = 16, fleet_array = '204,8;205,5;206,3', fleet_universe = 1, fleet_start_time = 1463355520, fleet_end_stay = 1463355520, fleet_end_time = 1463355578, fleet_start_id = 1, fleet_start_galaxy = 1, fleet_start_system = 1, fleet_start_planet = 1, fleet_start_type = 1, fleet_end_id = 5, fleet_end_galaxy = 1, fleet_end_system = 1, fleet_end_planet = 6, fleet_end_type = 1, fleet_resource_metal = 0, fleet_resource_crystal = 0, fleet_resource_deuterium = 0, fleet_group = 0, fleet_target_obj = 0, called = '0', tickinicial = 0, tickfinal = 9, tickretorno = 18, start_time = 1463355462; INSERT INTO uni1_fleet_event SET fleetID = @fleetID, `time` = 1463355520; INSERT INTO uni1_log_fleets SET fleet_id = @fleetID, fleet_owner = 1, fleet_target_owner = 4, fleet_mission = 1, fleet_amount = 16, fleet_array = '204,8,205,5,206,3', fleet_universe = 1, fleet_start_time = 1463355520, fleet_end_stay = 1463355520, fleet_end_time = 1463355578, fleet_start_id = 1, fleet_start_galaxy = 1, fleet_start_system = 1, fleet_start_planet = 1, fleet_start_type = 1, fleet_end_id = 5, fleet_end_galaxy = 1, fleet_end_system = 1, fleet_end_planet = 6, fleet_end_type = 1, fleet_resource_metal = 0, fleet_resource_crystal = 0, fleet_resource_deuterium = 0, fleet_group = 0, fleet_target_obj = 0, tickinicial = 0, tickfinal = 9, tickretorno = 18, start_time = 1463355462; UNLOCK TABLES;
File: /includes/classes/class.Database.php (Line 274)
URL: http://localhost/beta7/game.php?page=shipyard&mode=defense
PHP: Version 5.6.15 [ apache2handler ]
MySQL: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $

Debug Track:
#0 /includes/classes/class.FleetFunctions.php(527): Database->multi_query('LOCK TABLE uni1...')
#1 /includes/pages/game/class.ShowShipyardPage.php(582): FleetFunctions::sendFleet(Array, '1', 1, 1, 1, 1, 1, 1, '4', '5', '1', '1', '6', '1', Array, 1463355520, 1463355520, 1463355578, '0', 9, 0)
#2 /game.php(40): ShowShipyardPage->show()
#3 {main}
Return to Game | Contact Support Ticket

**Comment by xteriumboy** [comment]
Please make a training test ,have some bug :(

**Comment by joancefet** [comment]
Execute the SQL Scripts in "UpdatesSQL" directory.

**Comment by xteriumboy** [comment]
training not work corect :(

and another bug 

6user+ admin
1user 5planet but hostile sector nothing

http://prnt.sc/b4lx5a
no hostile mission :(

**Comment by joancefet** [comment]
Working in full training system now.

**Comment by xteriumboy** [comment]
fresh , clean install 

Issue: Missing argument 20 for FleetFunctions::sendFleet(), called in /includes/pages/game/class.ShowBuildingsPage.php on line 484 and defined
File: /includes/classes/class.FleetFunctions.php (Line 416)
URL: http://localhost/beta7/game.php?page=buildings
PHP: Version 5.6.15 [ apache2handler ]
MySQL: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $

Debug Track:
#0 /includes/classes/class.FleetFunctions.php(416): errorHandler(2, 'Missing argumen...', 'C://xampp//htdocs...', 416, Array)
#1 /includes/pages/game/class.ShowBuildingsPage.php(484): FleetFunctions::sendFleet(Array, '6', 1, 1, 1, 1, 1, 1, '1', '1', '1', '1', '1', '1', Array, 1463408745, 1463408745, 1463408785, 0)
#2 /game.php(40): ShowBuildingsPage->show()
#3 {main}

**Comment by xteriumboy** [comment]
Fatal error: Call to undefined method BuildFunctions::getMaxConstructibleDomes() in C:\xampp\htdocs\beta7\includes\pages\game\class.ShowShipyardPage.php on line 327

**Comment by joancefet** [comment]
Clean install not updated and not working. You can update your server to last commit e execute the sql scripts.

**Comment by joancefet** [comment]
Working in full training system now. Wait pls.

**Comment by xteriumboy** [comment]
ok thanks

**Comment by joancefet** [comment]
Fixed and tested.

**Comment by xteriumboy** [comment]
Mesage training and galaxy message show 2 times !

[http://prnt.sc/b4w5ul](url)    message 
[http://prnt.sc/b4vxjs](url)     galaxy

**Comment by xteriumboy** [comment]
You have time to fix this training bug

**Comment by joancefet** [comment]
You can delete
line 15 - main_navigation.tpl
`<span class="mesages" {if $new_message == 0}style="display:none;"{/if}></span>`
line 63 - main_navigation.tpl
`{if $authlevel > 0} <a class="btn_menu" href="game.php?page=galaxy2" id="munu_galaxy" {if $manual_17_step == 0}onclick="starttraining9()"{/if}>{$LNG.alm_galaxy}2</a>{/if}`

I will not delete the line 63 why I'm developing a new module.
