### ISSUE TITLE
Hostal sector ?

### ISSUE THREAD

**Issue by xteriumboy** [joancefet/Beta7#5]
hostals victory lvl.0

To perform achievements, you need to win battles in Hostal sector. Progress resets every 24 hours.

Need to perform to achieve:
Win 20 battle in the Hostal sector.

Where is?

**Comment by joancefet** [comment]
This is not an issue That's a question.
hostile sector is where there are more than 5 planets colonized by another player

**Comment by xteriumboy** [comment]
6user+ admin
1user 5planet but hostile sector nothing

[http://prnt.sc/b4lx5a](url)

**Comment by xteriumboy** [comment]
no hostile mission :(
