### ISSUE TITLE
game.php?page=ship

### ISSUE THREAD

**Issue by xteriumboy** [joancefet/Beta7#6]
Issue: Unable to load template extends 'layout.full.tpl|page.ship.default.tpl'
File: /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php (Line 127)
URL: http://localhost/beta7/game.php?page=ship
PHP: Version 5.6.15 [ apache2handler ]
MySQL: mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $

Debug Track:
#0 /includes/libs/Smarty/sysplugins/smarty_internal_templatebase.php(374): Smarty_Internal_TemplateBase->fetch('extends:layout....', NULL, NULL, NULL, true)
#1 /includes/classes/class.template.php(142): Smarty_Internal_TemplateBase->display('extends:layout....')
#2 /includes/pages/game/class.AbstractPage.php(1115): template->display('extends:layout....')
#3 /includes/pages/game/class.ShowShipPage.php(29): AbstractPage->display('page.ship.defau...')
#4 /game.php(40): ShowShipPage->show()
#5 {main}

**Comment by joancefet** [comment]
This is not enable yet.
