### ISSUE TITLE
Hostal sector ?

### ISSUE THREAD

**Issue by xteriumboy** [joancefet/Beta7#9]
hostals victory lvl.0

To perform achievements, you need to win battles in Hostal sector. Progress resets every 24 hours.

Need to perform to achieve:
Win 20 battle in the Hostal sector.

Where is?

6user+ admin
1user 5planet but hostile sector nothing

http://prnt.sc/b4lx5a
no  Hostal sector mission :(

**Comment by joancefet** [comment]
You win 20 battles in 24 hours?

**Comment by xteriumboy** [comment]
Hostal sector not exist :(

**Comment by joancefet** [comment]
Yes, I will delete this achievement.
